### ISSUE TITLE
How to replace `nvim` with `nix-config` built one?

### ISSUE THREAD

**Issue by kolpav** [syberant/nix-neovim#1]
I really like this project mainly due to how it doesn't try to implement every plugin as a module I feel I have more control that way.
I would like to try replace `nvim` with mine from `nvim.buildNeovim`. I have tried using overlays but without much luck mainly due to me not knowing nix well enough.
Both HM module `nixpkgs.overlays` and `overlays.default`

```nix
            ({ pkgs, ...}: {
              nixpkgs.overlays = [
                (final: prev: {
                  nvim = args.nix-neovim.buildNeovim {
                    configuration = ./nix/home-manager/nvim/configuration.nix;
                  };
                })
              ];
            })
```

doesn't seem to do anything can you please help me?

**Comment by syberant** [comment]
I'm glad you like it! I wasn't aware other people were actually using it :)

I believe the package is named `neovim` inside of nixpkgs so maybe if you rename it to `neovim = args.nix-neovim.buildNeovim ...` it would work?

I [personally](https://github.com/syberant/nix-config/blob/2d72edaa82df6a8fb9429a24a7aae0b20ede2f00/configuration/home-manager/modules/neovim/default.nix) use it directly like this within home-manager:
```nix
home.packages = [ (nix-neovim.buildNeovim { configuration = ./configuration.nix; }) ];
```

The relevant setting for a system-wide install (without home-manager) is `environment.systemPackages`:
```nix
environment.systemPackages = [ (nix-neovim.buildNeovim { configuration = ./configuration.nix; }) ];
```

Note that `programs.neovim` uses its own function to wrap neovim so you'd have to do a bit of hacking to get it to work with that option.

Hope this helps! Please give some more details about your configuration (like how you eventually install neovim) if not.

**Comment by kolpav** [comment]
> I'm glad you like it! I wasn't aware other people were actually using it :)

Having great time actually, your project will work with light modifications for long time so I decided to start using it.

> I believe the package is named `neovim`

That was it 👍 got it working now thank you.

While I was reading your configs I have found this `plugin.setup."nvim-treesitter.configs"` I am not sure how this `<plugin_name>.configs` work does every plugin has it?

**Comment by syberant** [comment]
Lots of lua plugins have a `setup` function to configure them.
Telescope for example [just needs `plugin.setup.telescope = {}`](https://github.com/nvim-telescope/telescope.nvim#telescope-setup-structure).

`nvim-treesitter` is a bit unusual for putting it behind a `configs` module but [the idea is the same](https://github.com/nvim-treesitter/nvim-treesitter#modules), note that `plugin.setup."nvim-treesitter.configs"` is required as `plugin.setup.nvim-treesitter.configs` wouldn't work.

The relevant code from nix-neovim is [here](https://github.com/syberant/nix-neovim/blob/main/modules/plugin.nix#L38).

I'll close the issue now but feel free to ask when you have another question or run into problems :)
