### ISSUE TITLE
Unable to make LSP packages available in PATH

### ISSUE THREAD

**Issue by kolpav** [syberant/nix-neovim#2]
Hi, I don't know how to make anything available for `neovim` in `PATH` this is the only way how I managed to not get error about `bash-language-server` not available in PATH when opening `.sh` file.

```nix
{ pkgs, ... }: {
  output.plugins = with pkgs.vimPlugins; [ nvim-lspconfig ];

  output.config_file = ''
    lua <<EOF
      local on_attach = function(client, bufnr)
        local bufopts = { noremap=true, silent=true, buffer=bufnr }
        vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
      end

      require('lspconfig')['bashls'].setup {
        on_attach = on_attach,
        cmd = {"${pkgs.nodePackages.bash-language-server}/bin/bash-language-server"},
      }
    EOF
  '';
}
```

but just this should work no?

```nix
{ pkgs, ... }: {
  output.plugins = with pkgs.vimPlugins; [ nvim-lspconfig ];

  output.path.path = with pkgs; [
    nodePackages.bash-language-server
  ];

  output.config_file = ''
    lua <<EOF
      require('lspconfig')['bashls'].setup {}
    EOF
  '';
}
```

I tried both `impure` and `pure` for `output.path.style` but the error stays the same. Could you please help me?

Edit:

Checking the `nix-neovim-PATH` and everything seems ok `bash -> /nix/store/wim4mqpn8lxhhr10p2kd070hyj152lil-bash-5.1-p16/bin/bash` I'll try other languages maybe there's something specific about bash I am not getting.

**Comment by syberant** [comment]
Hmm, your second config is working on my machine :)
The exact thing Nix (and flakes especially) is supposed to prevent!

The bash you found is just the `bash` shell and not the language server, its binary is called `bash-language-server`.

Could you open nix-neovim with the second config and run `:checkhealth`?
You should see your purity mode and your entire PATH there, please post the result of `ls /nix/store/whatever-you-found-in-checkhealth-nix-neovim-PATH/bin` here.

I got:
```
~ ❯ ls /nix/store/l69x476rfzg6sq05b5hha87fyn2k6c3i-nix-neovim-PATH/bin
bash-language-server
```

**Comment by kolpav** [comment]
Well I really tried to make it work so after reading and I think understanding how `nix-neovim` work (the trick with reading jsons in lua is really clever btw) I decided to build my own neovim even if I end up recreating most of the `nix-neovim` after a while:)

> The bash you found is just the bash shell and not the language server, its binary is called bash-language-server.

That was a typo I wanted to show that my `:checkhealth` is passing and the language server is there but copy pasted wrong bash line.

as I said I am no longer using `nix-neovim` instead I am doing this, just two big files `neovim.nix`, `init.lua` till I modularize it further. Everything seems to work except I think I am not at the "pure" level because of nvim path prefixing, replacing it didn't really worked.

```nix
{ pkgs, lib, ... }: {
  home.packages = [
    (pkgs.neovim.override {
      configure =
        let
          vimBinPath = with pkgs; lib.makeBinPath (
            # Common deps
            [ manix ripgrep fd git ] ++
            # Nix
            [ rnix-lsp nixfmt ] ++
            # HTML CSS JSON ESlint
            [ nodePackages.vscode-langservers-extracted ] ++
            # Typescript
            [ nodePackages.typescript nodePackages.typescript-language-server ] ++
            # Bash
            [ nodePackages.bash-language-server ] ++
            # Lua
            [ sumneko-lua-language-server ]
          );
        in
        {
          viAlias = true;
          vimAlias = true;
          withPython3 = true;
          withNodeJs = true;
          withRuby = true;
          extraMakeWrapperArgs = with pkgs; "--prefix PATH : ${vimBinPath}";
          customRC = ''
            lua << EOF
              vim.g.vimBinPath = "${vimBinPath}";
              vim.env.PATH = "${vimBinPath}";
              vim.g.copilot_node_command = "${pkgs.nodejs-16_x}/bin/node";
            EOF
            luafile ${./init.lua}
          '';
          packages.myNeovimPackages = with pkgs.vimPlugins; {
            start =
              # Explorer
              [ nvim-tree-lua nvim-web-devicons ] ++
              # Colorscheme
              [ nightfox-nvim ] ++
              # AST
              [ nvim-treesitter.withAllGrammars ] ++
              # LSP
              [ nvim-lspconfig lspkind-nvim lsp_signature-nvim ] ++
              # nix
              [ vim-nix ] ++
              # telescope
              [ 
                telescope-nvim
                telescope-live-grep-args-nvim 
                telescope-manix 
                telescope-fzf-native-nvim
              ] ++
              # comments
              [ nvim-comment ] ++
              # code completition
              [ 
                nvim-cmp 
                cmp-path 
                cmp-nvim-lsp 
                cmp-buffer 
                cmp-copilot 
                cmp_luasnip
                cmp-nvim-lsp-signature-help
              ] ++
              # null-ls
              [ null-ls-nvim plenary-nvim ] ++
              # gitsigns
              [ gitsigns-nvim ] ++
              # bufferline
              [ bufferline-nvim ] ++
              # whichkey
              [ which-key-nvim ] ++
              # copilot
              [ copilot-vim ] ++
              # multi-cursor
              [ vim-visual-multi ] ++
              # surround motions
              [ nvim-surround  nvim-treesitter-textobjects ] ++
              # jumps
              [ hop-nvim ] ++
              # treesitter context
              [ nvim-treesitter-context ] ++
              # Errors
              [ trouble-nvim ] ++
              # Snippets
              [ luasnip ];
            opt = [ ];
          };
        };
    })
  ];
}
```

Also while reading the code I found this, on my machine its `myNeovimPackages` instead of `myVimPackage` so command `NixNeovimPlugins` was opening empty directory for me but it totally could have been something on my side.

https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/plugin/plugin/nix-neovim.vim#L12

https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/modules/product.nix#L64

so I'll keep an eye on this project and your configs I might come back later but for now I'll close this issue as there is nothing to do and I am starting to think it was probably something I messed up as I am new to nix. Thank you for your help and this project!

**Comment by syberant** [comment]
> (the trick with reading jsons in lua is really clever btw)

Yeah, kind of proud of that one! It solved a lot of problems I had.

> I decided to build my own neovim even if I end up recreating most of the `nix-neovim` after a while:)

That might be for the best, feel free shoot me a message if you feel it's matured somewhat! I'd be interested to check it out and see which abstractions you've implemented.

`nix-neovim` is at present very unrefined and basically just enough to be able to use for my personal neovim config. Maybe I should put a slightly stronger warning in the README until I'm able to mature it a bit.

> > The bash you found is just the bash shell and not the language server, its binary is called bash-language-server.
> 
> That was a typo I wanted to show that my `:checkhealth` is passing and the language server is there but copy pasted wrong bash line.

Ah, OK. I'm still kind of confused why it's not working for you, I just saw something fishy on my side as well (normally nix-neovim-PATH should include a lot of standard tools as well like `awk` or `grep`).

> Also while reading the code I found this, on my machine its `myNeovimPackages` instead of `myVimPackage` so command `NixNeovimPlugins` was opening empty directory for me but it totally could have been something on my side.

Huh, it seems `nixpkgs` has apparently changed to using `myNeovimPackages`. It doesn't work for me either. Thanks for the bug report!

> so I'll keep an eye on this project and your configs I might come back later but for now I'll close this issue as there is nothing to do and I am starting to think it was probably something I messed up as I am new to nix. Thank you for your help and this project!

Thanks for checking out my toy project, good luck!
I'll put creating some debugging tools on my TODO list so problems like this might be easier to debug in the future :)

**Comment by kolpav** [comment]
@syberant 

> nix-neovim is at present very unrefined and basically just enough to be able to use for my personal neovim config

There are very few things you cannot do with it as of now so I would say its very near feature completion. It just takes a while to get its concepts if I were to add something to README it would be something like `# Architecture` basically describe process how you end up with your own neovim at the end


https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/modules/product.nix#L54

https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/modules/product.nix#L65

https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/modules/vim/options.nix#L29-L45

---


> Ah, OK. I'm still kind of confused why it's not working for you, I just saw something fishy on my side as well (normally nix-neovim-PATH should include a lot of standard tools as well like awk or grep).

The more I think about it the more it bugs me that I don't know why it was not working for me.
I think it should be easy to get to the point where its failing again for me with some minimal setup then I will reopen this issue and share my `flake.nix`, `flake.lock` so you can take a look.

Btw the not having `awk` `grep` and other gnu utils was exactly the error I was getting when I tried to make my neovim pure with `extraMakeWrapperArgs = with pkgs; "--set PATH '${vimEnvPath}'";` and `vimEnvPath = pkgs.symlinkJoin {`

**Comment by syberant** [comment]
I understand if you want to let this issue rest, but I do have a new idea after observing the fishy nix-neovim-PATH on my side.
It seems like `symlinkJoin` [isn't very good at handling nodejs executables](https://ertt.ca/blog/2022/01-12-nix-symlinkJoin-nodePackages/), perhaps you can find some warnings about this with `nix log /nix/store/<something-something>-nix-neovim-PATH`?
In this case the issue might well persist with your own configuration whenever you try bundling dependencies in a `symlinkJoin`.

**Comment by syberant** [comment]
> Btw the not having `awk` `grep` and other gnu utils was exactly the error I was getting when I tried to make my neovim pure with `extraMakeWrapperArgs = with pkgs; "--set PATH '${vimEnvPath}'";` and `vimEnvPath = pkgs.symlinkJoin {`

Yeah, Neovim by itself already needs some tools to function properly. I got around this by just [including `pkgs.stdenv.initialPath`](https://github.com/syberant/nix-neovim/blob/6f03a1c206ff2c5bea209c73f861ebd8088de53b/modules/output.nix#L74) which should have everything you need.

**Comment by kolpav** [comment]
Hi @syberant I am able to reproduce the error I cloned your `nix-config` repo and did these changes

Removed `modules/languages/config/latex.nix`

Added `nodePackages.bash-language-server` to
https://github.com/syberant/nix-config/blob/10513a54bcc44427326ec5cfa9439d578d309268/configuration/home-manager/modules/neovim/modules/languages/default.nix#L103

Added `bashls` to
https://github.com/syberant/nix-config/blob/10513a54bcc44427326ec5cfa9439d578d309268/configuration/home-manager/modules/neovim/modules/languages/default.nix#L59

Created `flake.nix`
```nix
{
  inputs = { nix-neovim.url = "github:syberant/nix-neovim"; };

  outputs = { self, nix-neovim }: {
    # For nix build
    defaultPackage."x86_64-linux" = nix-neovim.buildNeovim {
      configuration = ./configuration.nix;
      # pkgs = <your own instance of nixpkgs here>;
    };

    # For nix run
    defaultApp."x86_64-linux" = {
      type = "app";
      program = "${self.defaultPackage."x86_64-linux"}/bin/nvim";
    };
  };
}
```
`touch foo.sh && nix run .# foo.sh`

Take a look if you are interested why it fails. The way I use `nix-neovim` is that I stole few parts from it for my config so its ok if the error remains a mystery:)
